# action.yml
name: 'rust-cuda'
description: 'cargo test with CUDA libraries'
inputs: {}
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
