# action.yml
name: 'rust-cuda'
description: 'cargo test with CUDA libraries'
inputs:
  cuda-version:
    description: 'Version of CUDA libraries'
    required: true
    default: '10.2'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: ${{ inputs.cuda-version }}.Dockerfile
  args:
    - ${{ inputs.who-to-greet }}
