on: [push]

jobs:
  ubuntu1804-cuda10_2:
    runs-on: ubuntu-latest
    name: Ubuntu18.04, CUDA 10.2
    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      id: test
      uses: termoshtt/rust-cuda-docker-action@ubuntu1804-cuda10_2
      with:
        path: rust-cuda-test

  ubuntu1804-cuda10_1:
    runs-on: ubuntu-latest
    name: Ubuntu18.04, CUDA 10.1
    steps:
    - uses: actions/checkout@v1
    - name: cargo test
      id: test
      uses: termoshtt/rust-cuda-docker-action@ubuntu1804-cuda10_1
      with:
        path: rust-cuda-test
